baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Codadensys"

# googleAnalytics: "UA-000000-2"  # Placeholder for compatibility


summaryLength: 20

params:
  title: "Codadensys"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  googleAnalytics: "G-W38T3CNJ3D"

  favicons:
    themeColor: "#6A00FA"
    backgroundColor: "#1AC9FA"  # what does this do?
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "@codadensys"

  location:
    - "South Texas"
    
  contact:
    - "codadensys@gamail.com"
    - "555.555.5555"

  copyright: "©2024 Up Business All Rights Reserved"

menus:
  main:
    - name: "Product"
      url: "/#products"
      weight: 1

    - name: "How we work"
      url: "/#howwework"
      weight: 2

    - name: "Pricing"
      url: "/#pricing"
      weight: 3

    - name: "About Us"
      url: "/#aboutus"
      weight: 4


  buttons:
    - name: "Contact Us"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"


site:
  googleAnalytics: "G-W38T3CNJ3D"

themeOverrides: 
  colorPrimary: "#6A00FA"       # Primary Purple
  colorSecondary: "#1AC9FA"     # Bright Sky Blue
  colorThirdary: "#AAF8C2"      # Soft Mint Green
  neutralLight: "#FFFFFF"       # White
  neutralDark: "#1C1C1C"        # Dark Charcoal
  neutralTextLight: "#333333"   # Dark Gray for Text
  neutralTextDark: "#F5F5F5"    # Light Gray for Text
  accentPrimary: "#F88E8B"      # Soft Coral Red
  accentSecondary: "#F9C85E"    # Warm Golden Yellow
